import { Raleway } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import { Button } from "../components/Button";
import { HiMail } from "react-icons/hi";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const raleway = Raleway({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "600"],
});

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body
        className={`${raleway.className} min-h-full bg-[#F9EAE1] sm-w-[90%] max-w-[1200px] mx-auto`}
      >
        <header className="flex justify-between items-center py-8">
          <p className="text-lg font-semibold">Ọmọ́gẹ </p>
          <Button handleClick={() => {}}>
            Message <HiMail size={18} />
          </Button>
        </header>
        {children}
      </body>
    </html>
  );
}
