import { Onest } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const onest = Onest({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "600"],
});

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className={`${onest.className} min-h-full bg-[#F9EAE1] font-light`}>
        <section className="w-9/10 max-w-[1080px] mx-auto">{children}</section>
      </body>
    </html>
  );
}
